[
{"name": "CIT.MIC.01_Mathematical_Sciences", "size": 5, "imports": []},
{"name": "ERA.MIC.0101_Pure_Mathematics", "size": 5, "imports": []},
{"name": "CIT.MIC.0102_Applied_Mathematics", "size": 5, "imports": []},
{"name": "CIT.MIC.0103_Numerical_and_Computational_Mathematics", "size": 5, "imports": []},
{"name": "CIT.MIC.0104_Statistics", "size": 5, "imports": []},
{"name": "CIT.MIC.0105_Mathematical_Physics", "size": 5, "imports": []},
{"name": "CIT.MIC.0199_Other_Mathematical_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.02_Physical_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.0201_Astronomical_and_Space_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.0202_Atomic_Molecular_Nuclear_Particle_and_Plasma_Physics", "size": 5, "imports": []},
{"name": "CIT.PCE.0203_Classical_Physics", "size": 5, "imports": []},
{"name": "CIT.PCE.0204_Condensed_Matter_Physics", "size": 5, "imports": []},
{"name": "CIT.PCE.0205_Optical_Physics", "size": 5, "imports": []},
{"name": "CIT.PCE.0206_Quantum_Physics", "size": 5, "imports": []},
{"name": "CIT.PCE.0299_Other_Physical_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.03_Chemical_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.0301_Analytical_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0302_Inorganic_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0303_Macromolecular_and_Materials_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0304_Medicinal_and_Biomolecular_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0305_Organic_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0306_Physical_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0307_Theoretical_and_Computational_Chemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0399_Other_Chemical_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.04_Earth_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.0401_Atmospheric_Sciences", "size": 5, "imports": []},
{"name": "CIT.PCE.0402_Geochemistry", "size": 5, "imports": []},
{"name": "CIT.PCE.0403_Geology", "size": 5, "imports": []},
{"name": "CIT.PCE.0404_Geophysics", "size": 5, "imports": []},
{"name": "CIT.PCE.0405_Oceanography", "size": 5, "imports": []},
{"name": "CIT.PCE.0406_Physical_Geography_and_Environmental_Geoscience", "size": 5, "imports": []},
{"name": "CIT.PCE.0499_Other_Earth_Sciences", "size": 5, "imports": []},
{"name": "CIT.EE.05_Environmental_Sciences", "size": 5, "imports": []},
{"name": "CIT.EE.0501_Ecological_Applications", "size": 5, "imports": []},
{"name": "CIT.EE.0502_Environmental_Science_and_Management", "size": 5, "imports": []},
{"name": "CIT.EE.0503_Soil_Sciences", "size": 5, "imports": []},
{"name": "CIT.EE.0599_Other_Environmental_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.06_Biological_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.0601_Biochemistry_and_Cell_Biology", "size": 5, "imports": []},
{"name": "CIT.BB.0602_Ecology", "size": 5, "imports": []},
{"name": "CIT.BB.0603_Evolutionary_Biology", "size": 5, "imports": []},
{"name": "CIT.BB.0604_Genetics", "size": 5, "imports": []},
{"name": "CIT.BB.0605_Microbiology", "size": 5, "imports": []},
{"name": "CIT.BB.0606_Physiology", "size": 5, "imports": []},
{"name": "CIT.BB.0607_Plant_Biology", "size": 5, "imports": []},
{"name": "CIT.BB.0608_Zoology", "size": 5, "imports": []},
{"name": "CIT.BB.0699_Other_Biological_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.07_Agriculture_and_Veterinary_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.0701_Agriculture_Land_and_Farm_Management", "size": 5, "imports": []},
{"name": "CIT.BB.0702_Animal_Production", "size": 5, "imports": []},
{"name": "CIT.BB.0703_Crop_and_Pasture_Production", "size": 5, "imports": []},
{"name": "CIT.BB.0704_Fisheries_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.0705_Forestry_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.0706_Horticultural_Production", "size": 5, "imports": []},
{"name": "CIT.BB.0707_Veterinary_Sciences", "size": 5, "imports": []},
{"name": "CIT.BB.0799_Other_Agricultural_and_Veterinary_Sciences", "size": 5, "imports": []},
{"name": "ERA.MIC.08_Information_and_Computing_Sciences", "size": 5, "imports": []},
{"name": "ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing", "size": 5, "imports": []},
{"name": "ERA.MIC.0802_Computation_Theory_and_Mathematics", "size": 5, "imports": []},
{"name": "ERA.MIC.0803_Computer_Software", "size": 5, "imports": []},
{"name": "ERA.MIC.0804_Data_Format", "size": 5, "imports": []},
{"name": "ERA.MIC.0805_Distributed_Computing", "size": 5, "imports": []},
{"name": "ERA.MIC.0806_Information_Systems", "size": 5, "imports": []},
{"name": "ERA.MIC.0807_Library_and_Information_Studies", "size": 5, "imports": []},
{"name": "ERA.MIC.0899_Other_Information_and_Computing_Sciences", "size": 5, "imports": []},
{"name": "CIT.EE.09_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0901_Aerospace_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0902_Automotive_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0903_Biomedical_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0904_Chemical_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0905_Civil_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0906_Electrical_and_Electronic_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0907_Environmental_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0908_Food_Sciences", "size": 5, "imports": []},
{"name": "CIT.EE.0909_Geomatic_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0910_Manufacturing_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0911_Maritime_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0912_Materials_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0913_Mechanical_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0914_Resources_Engineering_and_Extractive_Metallurgy", "size": 5, "imports": []},
{"name": "CIT.EE.0915_Interdisciplinary_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.0999_Other_Engineering", "size": 5, "imports": []},
{"name": "CIT.EE.10_Technology", "size": 5, "imports": []},
{"name": "CIT.BB.1001_Agricultural_Biotechnology", "size": 5, "imports": []},
{"name": "CIT.BB.1002_Environmental_Biotechnology", "size": 5, "imports": []},
{"name": "CIT.BB.1003_Industrial_Biotechnology", "size": 5, "imports": []},
{"name": "CIT.MHS.1004_Medical_Biotechnology", "size": 5, "imports": []},
{"name": "ERA.EE.1005_Communications_Technologies", "size": 5, "imports": []},
{"name": "ERA.EE.1006_Computer_Hardware", "size": 5, "imports": []},
{"name": "CIT.EE.1007_Nanotechnology", "size": 5, "imports": []},
{"name": "CIT.EE.1099_Other_Technology", "size": 5, "imports": []},
{"name": "CIT.MHS.11_Medical_and_Health_Sciences", "size": 5, "imports": []},
{"name": "CIT.MHS.1101_Medical_Biochemistry_and_Metabolomics", "size": 5, "imports": []},
{"name": "CIT.MHS.1102_Cardiovascular_Medicine_and_Haematology", "size": 5, "imports": []},
{"name": "CIT.MHS.1103_Clinical_Sciences", "size": 5, "imports": []},
{"name": "CIT.MHS.1104_Complementary_and_Alternative_Medicine", "size": 5, "imports": []},
{"name": "CIT.MHS.1105_Dentistry", "size": 5, "imports": []},
{"name": "CIT.MHS.1106_Human_Movement_and_Sports_Science", "size": 5, "imports": []},
{"name": "CIT.MHS.1107_Immunology", "size": 5, "imports": []},
{"name": "CIT.MHS.1108_Medical_Microbiology", "size": 5, "imports": []},
{"name": "CIT.MHS.1109_Neurosciences", "size": 5, "imports": []},
{"name": "CIT.MHS.1110_Nursing", "size": 5, "imports": []},
{"name": "CIT.MHS.1111_Nutrition_and_Dietetics", "size": 5, "imports": []},
{"name": "CIT.MHS.1112_Oncology_and_Carcinogenesis", "size": 5, "imports": []},
{"name": "CIT.MHS.1113_Ophthalmology_and_Optometry", "size": 5, "imports": []},
{"name": "CIT.MHS.1114_Paediatrics_and_Reproductive_Medicine", "size": 5, "imports": []},
{"name": "CIT.MHS.1115_Pharmacology_and_Pharmaceutical_Sciences", "size": 5, "imports": []},
{"name": "CIT.MHS.1116_Medical_Physiology", "size": 5, "imports": []},
{"name": "CIT.MHS.1117_Public_Health_and_Health_Services", "size": 5, "imports": []},
{"name": "CIT.MHS.1199_Other_Medical_and_Health_Sciences", "size": 5, "imports": []},
{"name": "ERA.HCA.12_Built_Environment_and_Design", "size": 5, "imports": []},
{"name": "ERA.HCA.1201_Architecture", "size": 5, "imports": []},
{"name": "ERA.HCA.1202_Building", "size": 5, "imports": []},
{"name": "ERA.HCA.1203_Design_Practice_and_Management", "size": 5, "imports": []},
{"name": "ERA.HCA.1204_Engineering_Design", "size": 5, "imports": []},
{"name": "ERA.HCA.1205_Urban_and_Regional_Planning", "size": 5, "imports": []},
{"name": "ERA.HCA.1299_Other_Built_Environment_and_Design", "size": 5, "imports": []},
{"name": "ERA.EHS.13_Education", "size": 5, "imports": []},
{"name": "ERA.EHS.1301_Education_Systems", "size": 5, "imports": []},
{"name": "ERA.EHS.1302_Curriculum_and_Pedagogy", "size": 5, "imports": []},
{"name": "ERA.EHS.1303_Specialist_Studies_In_Education", "size": 5, "imports": []},
{"name": "ERA.EHS.1399_Other_Education", "size": 5, "imports": []},
{"name": "ERA.EC.14_Economics", "size": 5, "imports": []},
{"name": "ERA.EC.1401_Economic_Theory", "size": 5, "imports": []},
{"name": "ERA.EC.1402_Applied_Economics", "size": 5, "imports": []},
{"name": "ERA.EC.1403_Econometrics", "size": 5, "imports": []},
{"name": "ERA.EC.1499_Other_Economics", "size": 5, "imports": []},
{"name": "ERA.EC.15_Commerce_Management_Tourism_and_Services", "size": 5, "imports": []},
{"name": "ERA.EC.1501_Accounting_Auditing_and_Accountability", "size": 5, "imports": []},
{"name": "ERA.EC.1502_Banking_Finance_and_Investment", "size": 5, "imports": []},
{"name": "ERA.EC.1503_Business_and_Management", "size": 5, "imports": []},
{"name": "ERA.EC.1504_Commercial_Services", "size": 5, "imports": []},
{"name": "ERA.EC.1505_Marketing", "size": 5, "imports": []},
{"name": "ERA.EC.1506_Tourism", "size": 5, "imports": []},
{"name": "ERA.EC.1507_Transportation_and_Freight_Services", "size": 5, "imports": []},
{"name": "ERA.EC.1599_Other_Commerce_Management_Tourism_and_Services", "size": 5, "imports": []},
{"name": "ERA.EHS.16_Studies_In_Human_Society", "size": 5, "imports": []},
{"name": "ERA.EHS.1601_Anthropology", "size": 5, "imports": []},
{"name": "ERA.EHS.1602_Criminology", "size": 5, "imports": []},
{"name": "ERA.EHS.1603_Demography", "size": 5, "imports": []},
{"name": "ERA.EHS.1604_Human_Geography", "size": 5, "imports": []},
{"name": "ERA.EHS.1605_Policy_and_Administration", "size": 5, "imports": []},
{"name": "ERA.EHS.1606_Political_Science", "size": 5, "imports": []},
{"name": "ERA.EHS.1607_Social_Work", "size": 5, "imports": []},
{"name": "ERA.EHS.1608_Sociology", "size": 5, "imports": []},
{"name": "ERA.EHS.1699_Other_Studies_In_Human_Society", "size": 5, "imports": []},
{"name": "CIT.MHS.17_Psychology_and_Cognitive_Science", "size": 5, "imports": []},
{"name": "CIT.MHS.1701_Psychology", "size": 5, "imports": []},
{"name": "CIT.MHS.1702_Cognitive_Science", "size": 5, "imports": []},
{"name": "CIT.MHS.1799_Other_Psychology_and_Cognitive_Science", "size": 5, "imports": []},
{"name": "ERA.HCA.18_Law_and_Legal_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.1801_Law", "size": 5, "imports": []},
{"name": "ERA.HCA.1802_Maori_Law", "size": 5, "imports": []},
{"name": "ERA.HCA.1899_Other_Law_and_Legal_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.19_Studies_In_Creative_Arts_and_Writing", "size": 5, "imports": []},
{"name": "ERA.HCA.1901_Art_Theory_and_Criticism", "size": 5, "imports": []},
{"name": "ERA.HCA.1902_Film_Television_and_Digital_Media", "size": 5, "imports": []},
{"name": "ERA.HCA.1903_Journalism_and_Professional_Writing", "size": 5, "imports": []},
{"name": "ERA.HCA.1904_Performing_Arts_and_Creative_Writing", "size": 5, "imports": []},
{"name": "ERA.HCA.1905_Visual_Arts_and_Crafts", "size": 5, "imports": []},
{"name": "ERA.HCA.1999_Other_Studies_In_Creative_Arts_and_Writing", "size": 5, "imports": []},
{"name": "ERA.HCA.20_Language_Communication_and_Culture", "size": 5, "imports": []},
{"name": "ERA.HCA.2001_Communication_and_Media_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2002_Cultural_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2003_Language_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2004_Linguistics", "size": 5, "imports": []},
{"name": "ERA.HCA.2005_Literary_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2099_Other_Language_Literature_and_Culture", "size": 5, "imports": []},
{"name": "ERA.HCA.21_History_and_Archaeology", "size": 5, "imports": []},
{"name": "ERA.HCA.2101_Archaeology", "size": 5, "imports": []},
{"name": "ERA.HCA.2102_Curatorial_and_Related_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2103_Historical_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2199_Other_History_and_Archaeology", "size": 5, "imports": []},
{"name": "ERA.HCA.22_Philosophy_and_Religious_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2201_Applied_Ethics", "size": 5, "imports": []},
{"name": "ERA.HCA.2202_History_and_Philosophy_Of_Specific_Fields", "size": 5, "imports": []},
{"name": "ERA.HCA.2203_Philosophy", "size": 5, "imports": []},
{"name": "ERA.HCA.2204_Religion_and_Religious_Studies", "size": 5, "imports": []},
{"name": "ERA.HCA.2299_Other_Philosophy_and_Religious_Studies", "size": 5, "imports": []},
{"name":"UNI.Australian_Catholic_University","size":5,"imports":["ERA.EHS.13_Education","ERA.EHS.1301_Education_Systems","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EC.1503_Business_and_Management","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1606_Political_Science","ERA.EHS.1608_Sociology","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.21_History_and_Archaeology","ERA.HCA.2103_Historical_Studies","ERA.HCA.2201_Applied_Ethics"]},
{"name":"UNI.Australian_National_University","size":5,"imports":["CIT.MIC.0105_Mathematical_Physics","CIT.PCE.0302_Inorganic_Chemistry","CIT.PCE.0305_Organic_Chemistry","ERA.EC.1402_Applied_Economics","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.1905_Visual_Arts_and_Crafts"]},
{"name":"UNI.Bond_University","size":5,"imports":["CIT.MHS.1106_Human_Movement_and_Sports_Science","CIT.MHS.1111_Nutrition_and_Dietetics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1502_Banking_Finance_and_Investment","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law"]},
{"name":"UNI.Central_Queensland_University","size":5,"imports":["ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","CIT.EE.09_Engineering","CIT.MHS.1117_Public_Health_and_Health_Services"]},
{"name":"UNI.Charles_Darwin_University","size":5,"imports":["CIT.BB.06_Biological_Sciences","CIT.BB.0608_Zoology","CIT.BB.07_Agriculture_and_Veterinary_Sciences","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0802_Computation_Theory_and_Mathematics"]},
{"name":"UNI.Curtin_University_of_Technology","size":5,"imports":["CIT.MIC.01_Mathematical_Sciences","CIT.PCE.0206_Quantum_Physics","CIT.PCE.0406_Physical_Geography_and_Environmental_Geoscience","CIT.EE.05_Environmental_Sciences","CIT.BB.06_Biological_Sciences","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0806_Information_Systems","CIT.EE.0909_Geomatic_Engineering","CIT.EE.0914_Resources_Engineering_and_Extractive_Metallurgy","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1103_Clinical_Sciences","ERA.HCA.12_Built_Environment_and_Design","ERA.EHS.13_Education","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.1505_Marketing","ERA.EC.1506_Tourism","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1604_Human_Geography","ERA.EHS.1605_Policy_and_Administration","CIT.MHS.1702_Cognitive_Science","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2001_Communication_and_Media_Studies","ERA.HCA.21_History_and_Archaeology","ERA.HCA.2103_Historical_Studies"]},
{"name":"UNI.Deakin_University","size":5,"imports":["CIT.PCE.0301_Analytical_Chemistry","CIT.BB.06_Biological_Sciences","CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.BB.0602_Ecology","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0806_Information_Systems","ERA.EHS.1301_Education_Systems","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1502_Banking_Finance_and_Investment","ERA.EC.1503_Business_and_Management","ERA.EC.1504_Commercial_Services","ERA.EC.1505_Marketing","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1602_Criminology","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1902_Film_Television_and_Digital_Media","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2001_Communication_and_Media_Studies","ERA.HCA.2005_Literary_Studies","ERA.HCA.2102_Curatorial_and_Related_Studies","ERA.HCA.22_Philosophy_and_Religious_Studies","ERA.HCA.2202_History_and_Philosophy_Of_Specific_Fields","ERA.HCA.2203_Philosophy"]},
{"name":"UNI.Edith_Cowan_University","size":5,"imports":["CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.EE.09_Engineering","CIT.MHS.1106_Human_Movement_and_Sports_Science","CIT.MHS.1111_Nutrition_and_Dietetics","ERA.EC.1503_Business_and_Management","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.2001_Communication_and_Media_Studies"]},
{"name":"UNI.Flinders_University","size":5,"imports":["CIT.MIC.01_Mathematical_Sciences","CIT.PCE.02_Physical_Sciences","CIT.PCE.0202_Atomic_Molecular_Nuclear_Particle_and_Plasma_Physics","CIT.PCE.03_Chemical_Sciences","CIT.PCE.04_Earth_Sciences","CIT.PCE.0406_Physical_Geography_and_Environmental_Geoscience","CIT.EE.05_Environmental_Sciences","CIT.EE.0502_Environmental_Science_and_Management","CIT.BB.06_Biological_Sciences","CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.BB.0603_Evolutionary_Biology","CIT.BB.0605_Microbiology","CIT.BB.0608_Zoology","CIT.BB.07_Agriculture_and_Veterinary_Sciences","CIT.BB.0704_Fisheries_Sciences","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0806_Information_Systems","CIT.EE.09_Engineering","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1103_Clinical_Sciences","CIT.MHS.1109_Neurosciences","CIT.MHS.1114_Paediatrics_and_Reproductive_Medicine","CIT.MHS.1117_Public_Health_and_Health_Services","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1604_Human_Geography","ERA.EHS.1605_Policy_and_Administration","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1902_Film_Television_and_Digital_Media","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2005_Literary_Studies","ERA.HCA.21_History_and_Archaeology","ERA.HCA.2101_Archaeology","ERA.HCA.22_Philosophy_and_Religious_Studies","ERA.HCA.2203_Philosophy","ERA.HCA.2204_Religion_and_Religious_Studies"]},
{"name":"UNI.Griffith_University","size":5,"imports":["CIT.PCE.0306_Physical_Chemistry","CIT.PCE.04_Earth_Sciences","CIT.BB.06_Biological_Sciences","CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.BB.0603_Evolutionary_Biology","CIT.BB.0605_Microbiology","CIT.BB.07_Agriculture_and_Veterinary_Sciences","ERA.MIC.08_Information_and_Computing_Sciences","CIT.MHS.1103_Clinical_Sciences","CIT.MHS.1107_Immunology","CIT.MHS.1109_Neurosciences","CIT.MHS.1117_Public_Health_and_Health_Services","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EHS.13_Education","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1503_Business_and_Management","ERA.EC.1504_Commercial_Services","ERA.EHS.1604_Human_Geography","ERA.EHS.1605_Policy_and_Administration","CIT.MHS.17_Psychology_and_Cognitive_Science","CIT.MHS.1701_Psychology","ERA.HCA.1903_Journalism_and_Professional_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.1905_Visual_Arts_and_Crafts","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2004_Linguistics","ERA.HCA.2101_Archaeology"]},
{"name":"UNI.James_Cook_University","size":5,"imports":["CIT.PCE.02_Physical_Sciences","CIT.PCE.03_Chemical_Sciences","CIT.PCE.0405_Oceanography","CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.BB.0603_Evolutionary_Biology","CIT.BB.0605_Microbiology","CIT.BB.0608_Zoology","CIT.BB.07_Agriculture_and_Veterinary_Sciences","CIT.EE.09_Engineering","CIT.EE.0905_Civil_Engineering","CIT.EE.0915_Interdisciplinary_Engineering","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1102_Cardiovascular_Medicine_and_Haematology","CIT.MHS.1105_Dentistry","CIT.MHS.1110_Nursing","ERA.EHS.13_Education","ERA.EC.1506_Tourism","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1601_Anthropology","ERA.EHS.1604_Human_Geography","ERA.EHS.1608_Sociology","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2005_Literary_Studies"]},
{"name":"UNI.La_Trobe_University","size":5,"imports":["CIT.MIC.0102_Applied_Mathematics","CIT.EE.05_Environmental_Sciences","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0806_Information_Systems","CIT.MHS.11_Medical_and_Health_Sciences","ERA.EHS.13_Education","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1501_Accounting_Auditing_and_Accountability","ERA.EC.1506_Tourism","ERA.EC.1507_Transportation_and_Freight_Services","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1601_Anthropology","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.2002_Cultural_Studies","ERA.HCA.2005_Literary_Studies","ERA.HCA.22_Philosophy_and_Religious_Studies","ERA.HCA.2203_Philosophy"]},
{"name":"UNI.Macquarie_University","size":5,"imports":["CIT.PCE.03_Chemical_Sciences","CIT.BB.0601_Biochemistry_and_Cell_Biology","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0805_Distributed_Computing","ERA.MIC.0806_Information_Systems","CIT.EE.09_Engineering","CIT.EE.0903_Biomedical_Engineering","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EHS.13_Education","ERA.EHS.1301_Education_Systems","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1502_Banking_Finance_and_Investment","ERA.EC.1503_Business_and_Management","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1601_Anthropology","ERA.EHS.1604_Human_Geography","ERA.EHS.1606_Political_Science","ERA.EHS.1608_Sociology","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1902_Film_Television_and_Digital_Media","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.2002_Cultural_Studies","ERA.HCA.2003_Language_Studies","ERA.HCA.2101_Archaeology"]},
{"name":"UNI.Monash_University","size":5,"imports":["CIT.PCE.04_Earth_Sciences","CIT.PCE.0401_Atmospheric_Sciences","CIT.PCE.0403_Geology","CIT.PCE.0404_Geophysics","ERA.MIC.0804_Data_Format","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1201_Architecture","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.1506_Tourism","ERA.EHS.1601_Anthropology","ERA.EHS.1604_Human_Geography","ERA.EHS.1607_Social_Work"]},
{"name":"UNI.Murdoch_University","size":5,"imports":["CIT.PCE.03_Chemical_Sciences","CIT.EE.05_Environmental_Sciences","CIT.BB.06_Biological_Sciences","CIT.BB.0602_Ecology","CIT.BB.0605_Microbiology","CIT.BB.0607_Plant_Biology","CIT.BB.0608_Zoology","CIT.BB.07_Agriculture_and_Veterinary_Sciences","CIT.BB.0702_Animal_Production","CIT.BB.0704_Fisheries_Sciences","CIT.BB.0707_Veterinary_Sciences","CIT.EE.09_Engineering","CIT.EE.0907_Environmental_Engineering","CIT.EE.0914_Resources_Engineering_and_Extractive_Metallurgy","CIT.EE.10_Technology","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1117_Public_Health_and_Health_Services","ERA.EHS.13_Education","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.1505_Marketing","ERA.EC.1506_Tourism","ERA.EHS.16_Studies_In_Human_Society","CIT.MHS.1701_Psychology","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1902_Film_Television_and_Digital_Media","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2001_Communication_and_Media_Studies","ERA.HCA.2002_Cultural_Studies","ERA.HCA.2005_Literary_Studies","ERA.HCA.22_Philosophy_and_Religious_Studies"]},
{"name":"UNI.Queensland_University_of_Technology","size":5,"imports":["CIT.PCE.02_Physical_Sciences","CIT.PCE.0301_Analytical_Chemistry","CIT.PCE.04_Earth_Sciences","CIT.BB.06_Biological_Sciences","CIT.BB.0605_Microbiology","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0803_Computer_Software","ERA.MIC.0807_Library_and_Information_Studies","CIT.EE.0905_Civil_Engineering","CIT.MHS.1113_Ophthalmology_and_Optometry","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1201_Architecture","ERA.HCA.1202_Building","ERA.HCA.1203_Design_Practice_and_Management","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1501_Accounting_Auditing_and_Accountability","ERA.EC.1505_Marketing","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1602_Criminology","ERA.EHS.1607_Social_Work","CIT.MHS.1701_Psychology","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1902_Film_Television_and_Digital_Media","ERA.HCA.1903_Journalism_and_Professional_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.1905_Visual_Arts_and_Crafts"]},
{"name":"UNI.RMIT_University","size":5,"imports":["CIT.MIC.01_Mathematical_Sciences","ERA.MIC.08_Information_and_Computing_Sciences","CIT.EE.0908_Food_Sciences","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1104_Complementary_and_Alternative_Medicine","ERA.EHS.13_Education","ERA.EHS.1301_Education_Systems","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.1402_Applied_Economics","ERA.EC.1502_Banking_Finance_and_Investment","ERA.EC.1505_Marketing","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1605_Policy_and_Administration","ERA.EHS.1608_Sociology","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1902_Film_Television_and_Digital_Media","ERA.HCA.1904_Performing_Arts_and_Creative_Writing"]},
{"name":"UNI.Southern_Cross_University","size":5,"imports":["CIT.BB.06_Biological_Sciences","CIT.EE.09_Engineering","ERA.EHS.13_Education","ERA.EC.1506_Tourism","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1605_Policy_and_Administration"]},
{"name":"UNI.Swinburne_University_of_Technology","size":5,"imports":["CIT.MIC.01_Mathematical_Sciences","CIT.MIC.0102_Applied_Mathematics","CIT.BB.06_Biological_Sciences","CIT.BB.0605_Microbiology","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0804_Data_Format","ERA.MIC.0805_Distributed_Computing","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1117_Public_Health_and_Health_Services","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1203_Design_Practice_and_Management","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EC.1503_Business_and_Management","ERA.EC.1505_Marketing","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.21_History_and_Archaeology","ERA.HCA.2103_Historical_Studies"]},
{"name":"UNI.University_of_Adelaide","size":5,"imports":["CIT.PCE.0305_Organic_Chemistry","CIT.BB.0605_Microbiology","CIT.BB.0608_Zoology","CIT.BB.0702_Animal_Production","ERA.MIC.0803_Computer_Software","CIT.EE.10_Technology","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1201_Architecture","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1505_Marketing","ERA.EHS.1601_Anthropology","ERA.EHS.1606_Political_Science","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.20_Language_Communication_and_Culture"]},
{"name":"UNI.University_of_Canberra","size":5,"imports":["ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0806_Information_Systems","CIT.MHS.11_Medical_and_Health_Sciences","ERA.EHS.13_Education","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1605_Policy_and_Administration","ERA.EHS.1606_Political_Science","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2001_Communication_and_Media_Studies"]},
{"name":"UNI.University_of_Melbourne","size":5,"imports":["CIT.MIC.0105_Mathematical_Physics","CIT.PCE.0305_Organic_Chemistry","CIT.BB.0606_Physiology","CIT.BB.0703_Crop_and_Pasture_Production","CIT.EE.0908_Food_Sciences","CIT.EE.0909_Geomatic_Engineering","CIT.EE.0914_Resources_Engineering_and_Extractive_Metallurgy","ERA.HCA.1202_Building","ERA.EHS.1602_Criminology","ERA.HCA.1903_Journalism_and_Professional_Writing","ERA.HCA.1905_Visual_Arts_and_Crafts","ERA.HCA.2101_Archaeology","ERA.HCA.2204_Religion_and_Religious_Studies"]},
{"name":"UNI.University_of_New_England","size":5,"imports":["CIT.PCE.03_Chemical_Sciences","ERA.EHS.13_Education","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1604_Human_Geography","ERA.EHS.1605_Policy_and_Administration","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2004_Linguistics","ERA.HCA.2005_Literary_Studies","ERA.HCA.21_History_and_Archaeology","ERA.HCA.2101_Archaeology","ERA.HCA.2103_Historical_Studies","ERA.HCA.22_Philosophy_and_Religious_Studies","ERA.HCA.2203_Philosophy"]},
{"name":"UNI.University_of_New_South_Wales","size":5,"imports":["CIT.PCE.0201_Astronomical_and_Space_Sciences","CIT.PCE.0202_Atomic_Molecular_Nuclear_Particle_and_Plasma_Physics","CIT.PCE.0302_Inorganic_Chemistry","CIT.PCE.0305_Organic_Chemistry","CIT.BB.0603_Evolutionary_Biology","CIT.BB.0608_Zoology","ERA.MIC.0807_Library_and_Information_Studies","CIT.EE.0913_Mechanical_Engineering","CIT.MHS.1106_Human_Movement_and_Sports_Science","CIT.MHS.1108_Medical_Microbiology","CIT.MHS.1112_Oncology_and_Carcinogenesis","CIT.MHS.1113_Ophthalmology_and_Optometry","CIT.MHS.1114_Paediatrics_and_Reproductive_Medicine","CIT.MHS.1117_Public_Health_and_Health_Services","ERA.HCA.1201_Architecture","ERA.HCA.1202_Building","ERA.EC.1506_Tourism","ERA.EHS.1601_Anthropology","ERA.EHS.1602_Criminology","ERA.EHS.1607_Social_Work","ERA.EHS.1699_Other_Studies_In_Human_Society","ERA.HCA.2004_Linguistics"]},
{"name":"UNI.University_of_Newcastle","size":5,"imports":["CIT.PCE.02_Physical_Sciences","CIT.PCE.0304_Medicinal_and_Biomolecular_Chemistry","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","CIT.EE.0915_Interdisciplinary_Engineering","CIT.MHS.1103_Clinical_Sciences","CIT.MHS.1199_Other_Medical_and_Health_Sciences","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1201_Architecture","ERA.HCA.1202_Building","ERA.EHS.13_Education","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1604_Human_Geography","ERA.EHS.1605_Policy_and_Administration","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2004_Linguistics","ERA.HCA.22_Philosophy_and_Religious_Studies"]},
{"name":"UNI.University_of_Queensland","size":5,"imports":["CIT.MIC.0105_Mathematical_Physics","CIT.PCE.0305_Organic_Chemistry","CIT.BB.0702_Animal_Production","CIT.EE.0914_Resources_Engineering_and_Extractive_Metallurgy","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EHS.1601_Anthropology","ERA.HCA.1901_Art_Theory_and_Criticism"]},
{"name":"UNI.University_of_South_Australia","size":5,"imports":["ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0805_Distributed_Computing","ERA.MIC.0806_Information_Systems","CIT.MHS.1117_Public_Health_and_Health_Services","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EHS.13_Education","ERA.EHS.1301_Education_Systems","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.1402_Applied_Economics","ERA.EC.15_Commerce_Management_Tourism_and_Services","ERA.EC.1501_Accounting_Auditing_and_Accountability","ERA.EC.1506_Tourism","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1607_Social_Work","ERA.EHS.1608_Sociology","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1903_Journalism_and_Professional_Writing","ERA.HCA.1905_Visual_Arts_and_Crafts","ERA.HCA.2004_Linguistics"]},
{"name":"UNI.University_of_Southern_Queensland","size":5,"imports":["CIT.MIC.01_Mathematical_Sciences","CIT.PCE.02_Physical_Sciences","CIT.BB.07_Agriculture_and_Veterinary_Sciences","CIT.EE.09_Engineering","ERA.HCA.21_History_and_Archaeology"]},
{"name":"UNI.University_of_Sydney","size":5,"imports":["CIT.MIC.0105_Mathematical_Physics","CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.BB.0605_Microbiology","CIT.BB.0702_Animal_Production","CIT.BB.0703_Crop_and_Pasture_Production","CIT.EE.0903_Biomedical_Engineering","CIT.EE.0904_Chemical_Engineering","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1203_Design_Practice_and_Management","ERA.HCA.1205_Urban_and_Regional_Planning","ERA.EHS.1301_Education_Systems","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EC.1401_Economic_Theory","ERA.EC.1403_Econometrics","ERA.EC.1502_Banking_Finance_and_Investment","ERA.EHS.1602_Criminology","ERA.EHS.1607_Social_Work","ERA.HCA.2004_Linguistics","ERA.HCA.2201_Applied_Ethics"]},
{"name":"UNI.University_of_the_Sunshine_Coast","size":5,"imports":["CIT.BB.0705_Forestry_Sciences","CIT.MHS.11_Medical_and_Health_Sciences","CIT.MHS.1106_Human_Movement_and_Sports_Science","CIT.MHS.17_Psychology_and_Cognitive_Science","CIT.MHS.1701_Psychology"]},
{"name":"UNI.University_of_Western_Australia","size":5,"imports":["CIT.MIC.01_Mathematical_Sciences","CIT.MIC.0105_Mathematical_Physics","CIT.PCE.03_Chemical_Sciences","CIT.PCE.0302_Inorganic_Chemistry","CIT.BB.0702_Animal_Production","ERA.MIC.0802_Computation_Theory_and_Mathematics","ERA.MIC.0806_Information_Systems","CIT.EE.0907_Environmental_Engineering","CIT.EE.0913_Mechanical_Engineering","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1201_Architecture","ERA.EHS.1302_Curriculum_and_Pedagogy","ERA.EC.14_Economics","ERA.EC.1402_Applied_Economics","ERA.EC.1502_Banking_Finance_and_Investment","ERA.EC.1505_Marketing","ERA.EHS.1601_Anthropology","ERA.EHS.1604_Human_Geography","ERA.HCA.18_Law_and_Legal_Studies","ERA.HCA.1801_Law","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1901_Art_Theory_and_Criticism","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2004_Linguistics","ERA.HCA.2101_Archaeology","ERA.HCA.22_Philosophy_and_Religious_Studies","ERA.HCA.2203_Philosophy"]},
{"name":"UNI.University_of_Western_Sydney","size":5,"imports":["ERA.MIC.0101_Pure_Mathematics","CIT.PCE.03_Chemical_Sciences","CIT.PCE.0301_Analytical_Chemistry","CIT.BB.0601_Biochemistry_and_Cell_Biology","CIT.BB.0608_Zoology","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","CIT.EE.0913_Mechanical_Engineering","CIT.MHS.1103_Clinical_Sciences","CIT.MHS.1106_Human_Movement_and_Sports_Science","CIT.MHS.1109_Neurosciences","CIT.MHS.1114_Paediatrics_and_Reproductive_Medicine","ERA.HCA.12_Built_Environment_and_Design","ERA.HCA.1202_Building","ERA.EHS.13_Education","ERA.EHS.1301_Education_Systems","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EHS.16_Studies_In_Human_Society","ERA.EHS.1602_Criminology","ERA.EHS.1608_Sociology","ERA.EHS.1699_Other_Studies_In_Human_Society","CIT.MHS.17_Psychology_and_Cognitive_Science","CIT.MHS.1702_Cognitive_Science","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.2001_Communication_and_Media_Studies","ERA.HCA.2005_Literary_Studies","ERA.HCA.21_History_and_Archaeology","ERA.HCA.2102_Curatorial_and_Related_Studies","ERA.HCA.22_Philosophy_and_Religious_Studies","ERA.HCA.2203_Philosophy","ERA.HCA.2204_Religion_and_Religious_Studies"]},
{"name":"UNI.University_of_Wollongong","size":5,"imports":["CIT.PCE.02_Physical_Sciences","CIT.EE.05_Environmental_Sciences","CIT.BB.06_Biological_Sciences","CIT.BB.0602_Ecology","ERA.MIC.08_Information_and_Computing_Sciences","ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0803_Computer_Software","ERA.EHS.13_Education","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.14_Economics","ERA.EHS.1608_Sociology","CIT.MHS.17_Psychology_and_Cognitive_Science","ERA.HCA.19_Studies_In_Creative_Arts_and_Writing","ERA.HCA.1904_Performing_Arts_and_Creative_Writing","ERA.HCA.1905_Visual_Arts_and_Crafts","ERA.HCA.2001_Communication_and_Media_Studies","ERA.HCA.22_Philosophy_and_Religious_Studies"]},
{"name":"UNI.Victoria_University","size":5,"imports":["ERA.MIC.0801_Artificial_Intelligence_and_Image_Processing","ERA.MIC.0805_Distributed_Computing","ERA.MIC.0806_Information_Systems","ERA.EHS.13_Education","ERA.EHS.1303_Specialist_Studies_In_Education","ERA.EC.1506_Tourism","ERA.HCA.20_Language_Communication_and_Culture","ERA.HCA.2002_Cultural_Studies"]}
]